# Generated by Django 4.2.17 on 2025-05-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mfhouse.permissions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vi_address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=800)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to=mfhouse.permissions.PathAndRename('user_images'))),
                ('address_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id_date', models.DateField(blank=True, null=True)),
                ('national_id_address', models.CharField(blank=True, max_length=255, null=True)),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to=mfhouse.permissions.PathAndRename('id_cards'))),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to=mfhouse.permissions.PathAndRename('id_cards'))),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('show_bio', models.BooleanField(default=True)),
                ('show_phone_number', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], default='tenant', max_length=10)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='vi_address.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='vi_address.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infor', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='vi_address.ward')),
            ],
        ),
    ]
